// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXw5ma2kGkXYX0373raJyXS90l38S4BYw',
    appId: '1:1074070918946:web:8542de61f3b8a0ad91777b',
    messagingSenderId: '1074070918946',
    projectId: 'parcode-2fd8b',
    authDomain: 'parcode-2fd8b.firebaseapp.com',
    storageBucket: 'parcode-2fd8b.appspot.com',
    measurementId: 'G-9V2V8MM9F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRYVtU1m36aPXf2Mqy6w8yG4OsrBwnC0',
    appId: '1:1074070918946:android:c37303e97d53e94091777b',
    messagingSenderId: '1074070918946',
    projectId: 'parcode-2fd8b',
    storageBucket: 'parcode-2fd8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbpkdicreTpX9ZPqWzG_hftn_vy4gzWs',
    appId: '1:1074070918946:ios:94f1a8995a97d67c91777b',
    messagingSenderId: '1074070918946',
    projectId: 'parcode-2fd8b',
    storageBucket: 'parcode-2fd8b.appspot.com',
    iosBundleId: 'com.example.parcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAbpkdicreTpX9ZPqWzG_hftn_vy4gzWs',
    appId: '1:1074070918946:ios:d2d5b4b0afd932b191777b',
    messagingSenderId: '1074070918946',
    projectId: 'parcode-2fd8b',
    storageBucket: 'parcode-2fd8b.appspot.com',
    iosBundleId: 'com.example.parcode.RunnerTests',
  );
}
